[package]
authors     = ["Genkit Team <genkit-dev@google.com>"]
description = "Genkit AI framework core libraries."
edition     = "2021"
license     = "Apache-2.0"
name        = "genkit-core"
repository  = "https://github.com/firebase/genkit"
version     = "0.1.0"

[dependencies]
# Async runtime
tokio      = { version = "1", features = ["full"] }
tokio-util = { version = "0.7" }

# Serialization and Deserialization
serde      = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# JSON Schema generation
jsonschema = "0.17"
schemars   = "0.8"

# Tracing and Telemetry
opentelemetry      = { version = "0.22" }
opentelemetry_sdk  = { version = "0.22", features = ["rt-tokio"] }
tracing            = "0.1"
tracing-subscriber = "0.3"

# Error handling
thiserror = "1.0"

# Async traits
async-trait = "0.1"

# Others
futures = "0.3"
pin-project = "1.1.10"
pin-project-lite = "0.2.16"

[dev-dependencies]
# For testing
tokio-test = "0.4"
